### ISSUE TITLE
app停止运行。

### ISSUE THREAD

**Issue by java603889** [mylhyl/Android-CircleDialog#9]
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.mylhyl.circledialog.params.CircleParams)
                                                                 at android.os.Parcel.writeSerializable(Parcel.java:1279)
                                                                 at android.os.Parcel.writeValue(Parcel.java:1233)
                                                                 at android.os.Parcel.writeMapInternal(Parcel.java:591)
                                                                 at android.os.Bundle.writeToParcel(Bundle.java:1627)
                                                                 at android.os.Parcel.writeBundle(Parcel.java:605)
                                                                 at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:137)
                                                                 at android.os.Parcel.writeTypedArray(Parcel.java:1102)
                                                                 at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:385)
                                                                 at android.os.Parcel.writeParcelable(Parcel.java:1254)
                                                                 at android.os.Parcel.writeValue(Parcel.java:1173)
                                                                 at android.os.Parcel.writeMapInternal(Parcel.java:591)
                                                                 at android.os.Bundle.writeToParcel(Bundle.java:1627)
                                                                 at android.os.Parcel.writeBundle(Parcel.java:605)
                                                                 at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2252)
                                                                 at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3052)
                                                                 at android.os.Handler.handleCallback(Handler.java:725)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:92)
                                   circledialog                              at android.os.Looper.loop(Looper.java:137)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:511)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                              Caused by: java.io.NotSerializableException: com.mylhyl.circledialog.AbsCircleDialog
                                                                 at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1364)
                                                                 at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
                                                                 at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
                                                                 at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)

**Comment by mylhyl** [comment]
什么使用场景，旋转屏幕？
